name: Gitflow Test

on:
  workflow_dispatch:

jobs:
  gitflow:
    name: Gitflow
    runs-on: ubuntu-latest
    steps:
      - name: Setup gitflow
        run: |
          curl --silent --location  https://raw.githubusercontent.com/petervanderdoes/gitflow-avh/develop/contrib/gitflow-installer.sh --output ./gitflow-installer.sh
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run gitflow commands
        run: |
          git-flow --version
