on:
  repository_dispatch:
    types: release-event

jobs:
  preset:
    runs-on: ubuntu-latest
    steps:
    - name: Test
      run: echo ${{ github.event.client_payload.trigger }}
  release:
    if: ${{ github.event.client_payload.trigger }} == 'release'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        name: ${{ github.event.client-payload.repo }}
        submodules: true
        fetch-depth: 0
        refs: 'develop'
    - name: Check repository
      run: |
        git remote --v
    - name: Echo passed payload
      run: |
        echo ${{ github.event.client-payload.option }}
        echo ${{ github.event.client-payload.trigger }}
